export default () => {
    // <!-- generated by https://loading.io/ -->
    //  style="margin-right:-2px;display:block;background-repeat-y:initial;background-repeat-x:initial;background-color:rgb(241, 242, 243);animation-play-state:paused"
    // animation-play-state:paused
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            xmlnsXlink="http://www.w3.org/1999/xlink"
            viewBox="0 0 100 100"
            preserveAspectRatio="xMidYMid">
            <circle
                cx="50"
                cy="50"
                r="32"
                strokeWidth={8}
                stroke="#b3c430"
                strokeDasharray="50.26548245743669 50.26548245743669"
                fill="none"
                strokeLinecap="round"
                transform="matrix(1,0,0,1,0,0)"
                style={{
                    transform: 'matrix(1, 0, 0, 1, 0, 0)',
                }} />
        </svg>
    );
};
